linters:
    enable-all: true

linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: emperror.dev/handler/stackdriver

service:
    golangci-lint-version: 1.17.x
