linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: emperror.dev/handler/stackdriver

linters:
    enable-all: true
    disable:
        - funlen
        - wsl

        # TODO: fixme
        - godox

service:
    golangci-lint-version: 1.21.x
